### PR TITLE
Cleaned up code, fixed a few typos, and worked on getting bettter score on Pylint

### PR DESCRIPTION
**Pull request by MichaelK760**
This has a lot of changes that gives a better score on pylint which might be a good thing

### CODE REVIEW

**Comment by MichaelK760** [comment]
Also added a functionality where if the program cannot detect a hostname, it will return false

**Comment by maraslidilara** [comment]
thanks, it looks better!

**Comment by MichaelK760** [comment]
Just added a feature to see if a port doesn't work

**Comment by dbachmann1408** [comment]
Good job everyone. I ran it and it has errors that we need to fix but because of your hard work and dedication I merged the new code. The next mission is to fix the errors.

**Pull request merged**
